sudo: false

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.8
          - g++-4.8
          - libboost-all-dev
          - bash-completion
      env:
        - CC=gcc-4.8
        - CXX=g++-4.8
        
        # set environment variables for boost
        - CASM_BOOST_INCLUDEDIR="/usr/include/"
        - CASM_BOOST_LIBDIR="/usr/lib/x86_64-linux-gnu/"
        - CASM_BOOST_NO_CXX11_SCOPED_ENUMS=1

    - os: osx
      compiler: clang
      env:
        - CASM_BOOST_NO_CXX11_SCOPED_ENUMS=1
        

before_install:

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        CASM_NCPU=2;
        . /usr/share/bash-completion/bash_completion;
    fi
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        brew install boost@1.55 bash-completion;
        CASM_NCPU=2;
        . /sw/etc/bash_completion;
    fi
  
  # check g++ version
  - g++ --version
  
  # check python
  - python --version
  - python -c "import sys; print sys.path"
  
  # upgrade pip and install testing requirements
  - export PATH=`python -m site --user-site`/../../../bin:$PATH
  - pip install --upgrade pip
  - pip install --user -r python/casm/test_requirements.txt
  
  # check env
  - printenv
  

script: 
  - set -e
  - 'echo "CASM_NCPU: $CASM_NCPU"'
  
  # C++ and CLI
  - ./configure CXXFLAGS="-O3 -DNDEBUG -Wno-deprecated-declarations" --with-bash-completion-dir=$BASH_COMPLETION_DIR
  - make -j $CASM_NCPU
  - make check -j $CASM_NCPU

  # Python
  - cd python/casm
  - pip install --user .
  - pytest -r ap -s test_casm
