sudo: false

language: cpp

cache:
  - ccache
  diretories:
    - $HOME/.local/conda

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
          - bash-completion
          - curl

    - os: osx
      compiler: clang


install:
  - source $TRAVIS_BUILD_DIR/build_scripts/travis-install-$TRAVIS_OS_NAME.sh

  # check env
  - printenv

  # check g++ version
  - $GXX --version

  # check python
  - python --version
  - python -c "import sys; print(sys.path)"


script:
  - $TRAVIS_BUILD_DIR/build_scripts/travis-install-$TRAVIS_OS_NAME.sh
